### ISSUE TITLE
Does it Work for MacOS and Windows Platform

### ISSUE THREAD

**Issue by sasirven** [matthewrdev/UnityUaal.Maui#1]
Hi, juste a simple question here.

I saw you've mention Android and iOS, but does it work for Windows and MacOs ?

Thanks

**Comment by matthewrdev** [comment]
Hi @iShoFen, in theory the iOS version could be supported via MacCatalyst but I haven't tried it. For Windows, it depends on if Unity's "Unity As A Library" methodology is supported for exporting to Windows.

It's not in the scope of the product I'm building so I'm very unlikely to investigate either integration.

**Comment by sasirven** [comment]
Okey thank you for your fast Answer !

**Comment by matthewrdev** [comment]
No problem! Good luck 🤞
