### ISSUE TITLE
Advice for older Unity versions

### ISSUE THREAD

**Issue by peterplaybrush** [matthewrdev/UnityUaal.Maui#2]
Hi,

Thank you for sharing this project.
Can I just ask for some advice on how to get this to work with older versions of Unity?

I'm using Unity 2021.3.12f1 because that's what our project is implemented in.
I found for example that instead of UnityPlayerForActivityOrService class, the older Unity uses UnityPlayer class.
The methods in this are different.

Are these classes documented anywhere?
How can I know which method does what and when to call it?

**Comment by matthewrdev** [comment]
Hi @peterplaybrush, thanks for reaching out :)

I'm not sure about any documentation for the UnityPlayer class as I've only worked with the newer one.

Unfortunately , my best advice is to experiment with the older class and see how it works. You could compare it with the sample here to see if there are any overlapping methods and that should give you some direction.

Some other options are:

 * Upgrade your Unity projects.
 * Reach out to Unity support for help and see if they have any older samples of UAAL.

**Comment by peterplaybrush** [comment]
I'll probably end up upgrading to Unity 2023.
Thank you for your response.
Peter
